blank_issues_enabled: false
contact_links:
  - name: 项目讨论
    url: https://github.com/assumeengagetry/Kernal/discussions
    about: 请在这里讨论想法或提问
  - name: 贡献指南
    url: https://github.com/assumeengagetry/Kernal/blob/main/CONTRIBUTING.md
    about: 在提交issue前请查看贡献指南
