name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc nasm qemu-system-x86 gcc-multilib
        
    - name: Build kernel
      run: make kernel
      
    - name: Build userspace
      run: make user
      
    - name: Run tests
      run: make test
